# Generated by Django 3.2 on 2022-05-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PUBLIC', 'public'), ('PRIVATE', 'private')], max_length=15)),
                ('name', models.CharField(max_length=50)),
                ('content', models.TextField()),
            ],
        ),
    ]
