# Generated by Django 3.2 on 2022-04-19 15:39

from django.db import migrations
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', user.models.EmailUserManager()),
            ],
        ),
    ]
